#----------- РАСЧЕТ ТЕКУЩИЙ МЕСЯЦ -----------

- alias: power_conter_month  
  trigger:
    - platform: time
      at: "00:01:00"
  action:
    - service: mqtt.publish
      data:
        topic: "tele/power/month"
        payload_template: >
          {{ ((states.sensor.power_counter_month.state | float) + (states.sensor.potreblenie_vchera.state | float)) | round (2) }}
        retain: true


# ----------- РАСЧЕТ МЕСЯЦ И СБРОС -----------
- alias: power_conter_lastmonth  
  trigger:
    - platform: time
      at: "00:01:05"
  condition:
    - condition: template
      value_template: '{{ now().day == 1 }}'
  action:
    - service: mqtt.publish
      data:
        topic: "tele/power/lastmonth"
        payload_template: >
          {{ states.sensor.power_counter_month.state | float }}
        retain: true
    - delay: 00:00:01
    - service: mqtt.publish
      data:
        topic: "tele/power/month"
        payload_template: '{{ 0 }}'
        retain: true
