# integration broadlink RM Pro and others Broadlink devices

remote:
  - platform: broadlink
    host: 192.168.1.3
    mac: 'b4:43:0d:c3:06:3e'
    name: RM_Pro
    
    
  - platform: broadlink
    host: 192.168.1.7
    mac: 'b4:43:0d:c3:f8:71'
    name: e-Air
